name: ants
version: 0.1.0.0
github: "githubuser/ants"
license: BSD3
author: "Author name here"
maintainer: "isrothy@icloud.com"
copyright: "2023 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/ants#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - commonmark
  - commonmark-extensions
  - containers
  - cond
  - data-default
  - directory
  - either
  - extra
  - filepath
  - mtl
  - lens
  - loop
  - lsp
  - lsp-test
  - lsp-types
  - optparse-applicative
  - parsec
  - path
  - process
  - random
  - raw-strings-qq
  - regex-tdfa ^>= 1.3.2
  - safe
  - text
  - temporary
  - time
  - unliftio
  - unordered-containers
  - vector
  - yaml

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  ants:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ants
  ants-ls:
    main: Main.hs
    source-dirs: lsp
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ants

tests:
  ants-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - ants

benchmarks:
  ants-bench:
    main: Main.hs
    source-dirs: benchmarks
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - base
      - criterion
      - ants

