module Model.MarkdownAst.Lenses
  ( HasAlertType (..),
    HasAscii (..),
    HasBlock (..),
    HasChar (..),
    HasColAlignments (..),
    HasDefListItems (..),
    HasEmoji (..),
    HasFormat (..),
    HasHeaders (..),
    HasInline (..),
    HasHref (..),
    HasLabel (..),
    HasLanguage (..),
    HasLevel (..),
    HasListItems (..),
    HasListSpacing (..),
    HasListType (..),
    HasNumber (..),
    HasRows (..),
    HasTarget (..),
    HasTaskListItems (..),
    HasText (..),
    HasTitle (..),
  )
where

import Model.MarkdownAst.Lenses.HasAlertType
import Model.MarkdownAst.Lenses.HasAscii
import Model.MarkdownAst.Lenses.HasBlock
import Model.MarkdownAst.Lenses.HasChar
import Model.MarkdownAst.Lenses.HasColAlignments
import Model.MarkdownAst.Lenses.HasDefListItems
import Model.MarkdownAst.Lenses.HasEmoji
import Model.MarkdownAst.Lenses.HasFormat
import Model.MarkdownAst.Lenses.HasHeaders
import Model.MarkdownAst.Lenses.HasHref
import Model.MarkdownAst.Lenses.HasInline
import Model.MarkdownAst.Lenses.HasLabel
import Model.MarkdownAst.Lenses.HasLanguage
import Model.MarkdownAst.Lenses.HasLevel
import Model.MarkdownAst.Lenses.HasListItems
import Model.MarkdownAst.Lenses.HasListSpacing
import Model.MarkdownAst.Lenses.HasListType
import Model.MarkdownAst.Lenses.HasNumber
import Model.MarkdownAst.Lenses.HasRows
import Model.MarkdownAst.Lenses.HasTarget
import Model.MarkdownAst.Lenses.HasTaskListItems
import Model.MarkdownAst.Lenses.HasText
import Model.MarkdownAst.Lenses.HasTitle
